---
- name: Check for connectivity
  ping:
    data: alive


- name: create keyring directory
  file:
    path: /root/clickhouse_db_structure/
    owner: root
    group: root
    mode: 0755
    state: directory


- name: Generate SQL file from template
  template:
    src: templates/clickhouse_sql.j2
    dest: "/root/clickhouse_db_structure/clickhouse_commands_{{ ansible_hostname }}.sql"

- name: Execute SQL commands in ClickHouse container
  command:
    cmd: "docker exec {{ ansible_hostname }}-clickhouse clickhouse-client -u {{ CLICKHOUSE_USER }} --password {{ CLICKHOUSE_PASSWORD }} -q \"$(cat /root/clickhouse_db_structure/clickhouse_commands_{{ ansible_hostname }}.sql)\""
  environment:
    CLICKHOUSE_USER: "username"
    CLICKHOUSE_PASSWORD: "password"

- name: Remove generated SQL file
  file:
    path: "/tmp/clickhouse_commands_{{ ansible_hostname }}.sql"
    state: absent
