---
- name: setting up Clickhouse cluster
  hosts: all
  become: true
  tasks:
    - name: Include variables
      include_vars: "all.yaml"

    - name: Setting the basis on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Pre_Setup
        - $PWD/roles/OS_Tuning
        - $PWD/roles/Install_Docker


    - name: Deploy Clickhouse and Clickhouse_Keeper
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Install_Clickhouse
        - $PWD/roles/Install_Clickhouse_Keeper
      when: mode == 'clickhouse'


    - name: Set up the sql schema on clickhouse instances
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Clickhouse_Database_Setup_1Shard_3Replicas
      when: init_cluster == 'true'




    - name: Deploy Node exporter on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Node_Exporter

    - name: Set up the monitoring stack
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Victoria_Metrics
      when: mode == 'monitoring'



