---
- name: setting up Redis cluster
  hosts: all
  become: true
  tasks:
    - name: Include variables
      include_vars: "all.yaml"

    - name: Setting the basis on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Pre_Setup
        - $PWD/roles/OS_Tuning
        - $PWD/roles/Install_Docker


    - name: Deploy Clickhouse and Zookeper
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Install_Clickhouse
        - $PWD/roles/Install_Zookeper

      when: mode == 'clickhouse'



    - name: Deploy Node exporter on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Node_Exporter
      when: mode == 'monitoring'

    - name: Set up the monitoring stack
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Victoria_Metrics
      when: mode == 'monitoring'



